#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: iuf-install-
spec:
  podMetadata:
    annotations:
      sidecar.istio.io/inject: "false"    
  volumes:
    - name: ssh
      hostPath:
        path: /root/.ssh
        type: Directory
    - name: host-usr-bin
      hostPath:
        path: /usr/bin
        type: Directory
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
  # schedule workflow jobs asap
  priorityCLassName: system-node-critical
  # Pod GC strategy must be one of the following:
  # * OnPodCompletion - delete pods immediately when pod is completed (including errors/failures)
  # * OnPodSuccess - delete pods immediately when pod is successful
  # * OnWorkflowCompletion - delete pods when workflow is completed
  # * OnWorkflowSuccess - delete pods when workflow is successful
  podGC:
    strategy: OnPodCompletion
  # allow workflow jobs running on master node
  #   we may have a situation that all worker nodes
  #   are marked as "being rebuilt" (cray.nls=ncn-w001)
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      # try to use master nodes as much as possible
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          # process each product defined in iuf session
          {{ range $indexProduct,$product := $.Products }}
          # generate tasks based on stages defined in iuf session
          # Special handling:
          #   1. rolling-reboot is a global step that should run only once
          #   2. post-install-check should happen:
          #       2.1 after rolling-reboot if it is defined
          #       2.1 after other stages if rolling-reboot is NOT defined 
            {{ range $indexStage,$stage := $.Stages }}
              {{ if and (ne $stage "rolling-reboot") (ne $stage "post-install-check") }}
          - name: {{$product}}-{{$stage}}
            template: {{$stage}}
              {{ if ne $indexStage 0 }}
            dependencies:
              - {{$product}}-{{ index $.Stages (add $indexStage -1) }}
              {{ end }}
            arguments: 
              parameters:
              - name: product
                value: {{$product}}  
              - name: dryRun
                value:  "{{$.DryRun}}"
              {{ end }}
            {{ end }}
          {{ end }}

          # rolling-reboot if defined in iuf session
          {{ if has "rolling-reboot" $.Stages }}
          - name: rolling-reboot
            template: rolling-reboot
            dependencies:
              {{ range $indexProduct,$product := $.Products }}
                {{ range $indexStage,$stage := $.Stages }}
                  {{ if and (ne $stage "rolling-reboot") (ne $stage "post-install-check") }}
              - {{$product}}-{{$stage}}
                  {{ end }}
                {{ end }}
              {{ end }}
            arguments: 
              parameters:
              - name: dryRun
                value:  "{{$.DryRun}}"
          {{ end }}

          # post-install-check
          {{ if has "post-install-check" $.Stages }}
            {{ range $indexProduct,$product := $.Products }}
          - name: {{$product}}-post-install-check
            template: post-install-check
            dependencies:
              {{ if has "rolling-reboot" $.Stages }}
              - rolling-reboot
              {{ else }}
                {{ range $indexStage,$stage := $.Stages }}
                  {{ if and (ne $stage "rolling-reboot") (ne $stage "post-install-validation") }}
              - {{$product}}-{{$stage}}
                  {{ end }}
                {{ end }}
              {{ end }}
            arguments: 
              parameters:
              - name: product
                value: {{$product}}  
              - name: dryRun
                value:  "{{$.DryRun}}"
            {{ end }}
          {{ end }}
    # reference to individual tasks
    - name: pre-install-check
      inputs:
        parameters:
          - name: dryRun
          - name: product
      dag:
        tasks:
          - name: preflight-checks-for-services
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
    - name: deliver-product
      inputs:
        parameters:
          - name: dryRun
          - name: product
      dag:
        tasks:
          - name: generate-loftsman-manifests
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
          - name: s3-upload
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
          - name: nexus-upload
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
          - name: vcs-upload
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
          - name: ims-upload
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
          - name: loftsman-manifest-upload
            dependencies:
              - generate-loftsman-manifests
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
    - name: update-config
      inputs:
        parameters:
          - name: dryRun
          - name: product
      dag:
        tasks:
          - name: create-integration-branch
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
    - name: deploy-product
      inputs:
        parameters:
          - name: dryRun
          - name: product
      dag:
        tasks:
          - name: loftsman-manifest-deploy
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
          - name: activate-cray-product-catalog
            dependencies:
              - loftsman-manifest-deploy
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
    - name: sat-bootprep
      inputs:
        parameters:
          - name: dryRun
          - name: product
      dag:
        tasks:
          - name: sat-bootprep
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
    - name: rolling-reboot
      inputs:
        parameters:
          - name: dryRun
      dag:
        tasks:
          - name: rolling-reboot-ncn-master
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
          - name: rolling-reboot-ncn-worker
            dependencies:
              - rolling-reboot-ncn-master
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
          - name: rolling-reboot-ncn-storage
            dependencies:
              - rolling-reboot-ncn-worker
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
          - name: rolling-reboot-cn
            dependencies:
              - rolling-reboot-ncn-storage
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
    - name: post-install-check
      inputs:
        parameters:
          - name: dryRun
          - name: product
      dag:
        tasks:
          - name: wait-for-jobs
            templateRef:
              name: kubectl-and-curl-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{ `{{inputs.parameters.dryRun}}` }}"
                - name: scriptContent
                  value: |
                    echo TODO
