#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
version: 0.1.0 # IUF version

stages:
    - name: process-media
      type: product
      operations:
        - name: extract-release-distributions
          local-path: operations/extract-release-distributions.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: pre-install-check
      type: global
      operations:
        - name: preflight-checks-for-services
          local-path: operations/preflight-checks-for-services.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: deliver-product
      type: product
      operations:
        - name: loftsman-manifest-upload
          local-path: operations/loftsman-manifest-upload.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.
        - name: s3-upload
          local-path: operations/s3-upload.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.
        - name: nexus-setup
          local-path: operations/nexus-setup/nexus-setup-template.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: # any parameters that will be supplied statically to this operation.
            nexus-setup-image: artifactory.algol60.net/csm-docker/unstable/cray-nexus-setup:0.8.0-20221021164623-e8d3d3d
        - name: nexus-rpm-upload
          local-path: operations/nexus-setup/nexus-rpm-upload.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.
        - name: nexus-docker-upload
          local-path: operations/nexus-setup/nexus-docker-upload.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.
        - name: nexus-helm-upload
          local-path: operations/nexus-setup/nexus-helm-upload.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.
        - name: vcs-upload
          local-path: operations/vcs-upload.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.
        - name: ims-upload
          local-path: operations/ims-upload.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: update-vcs-config
      type: product
      operations:
        - name: update-working-branch
          local-path: operations/update-working-branch.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: update-cfs-config
      type: global
      operations:
        - name: update-cfs-config
          local-path: operations/update-cfs-config.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: deploy-product
      type: product
      operations:
        - name: loftsman-manifest-deploy
          local-path: operations/loftsman-manifest-deploy.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.
        - name: set-product-active
          local-path: operations/set-product-active.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: prepare-images
      type: global
      operations:
        - name: prepare-images
          local-path: operations/prepare-images.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: management-nodes-rollout
      type: global
      operations:
        - name: management-nodes-rollout
          local-path: operations/management-nodes-rollout.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: post-install-service-check
      type: product
      operations:
        - name: post-install-service-check
          local-path: operations/post-install-service-check.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: managed-nodes-rollout
      type: global
      operations:
        - name: managed-nodes-rollout
          local-path: operations/managed-nodes-rollout.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    - name: post-install-check
      type: product
      operations:
        - name: post-install-check
          local-path: operations/post-install-check.yaml # this is relative to stages.yaml, which is contained in workflows/iuf/ in docs-csm
          static-parameters: {} # any parameters that will be supplied statically to this operation.

    
