#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nexus-setup-template
  namespace: argo
spec:
  arguments:
    parameters:
    - name: product
    - name: product_host_path
    # The value for content is set to the json string value for 'content' in the manifest when --parameter-file is
    # set to the path of the IUF manifest yaml file.
    - name: content
  entrypoint: nexus-setup
  templates:
  - name: nexus-setup
    inputs:
      parameters:
      - name: content
        value: "{{workflow.parameters.content}}"
      - name: product
        value: "{{workflow.parameters.product}}"
      - name: product_host_path
        value: "{{workflow.parameters.product_host_path}}"
    nodeSelector:
      kubernetes.io/hostname: ncn-m001
    tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    container:
      image: artifactory.algol60.net/csm-docker/unstable/cray-nexus-setup:0.8.0-20221006225615_49737fe
      command: [iuf-nexus-setup]
      args: ["--blobstores","/products/{{workflow.parameters.product}}/{{=jsonpath(workflow.parameters.content,'$.nexus_blob_stores.yaml_path')}}","--repositories","/products/{{workflow.parameters.product}}/{{=jsonpath(workflow.parameters.content,'$.nexus_repositories.yaml_path')}}"]
      env:
      - name: NEXUS_URL
        value: "https://packages.local"
      - name: NEXUS_USERNAME
        valueFrom:
          secretKeyRef:
            name: nexus-admin-credential
            key: username
      - name: NEXUS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: nexus-admin-credential
            key: password
      volumeMounts:
      - name: products
        mountPath: /products
    # This will be an RBD mount.
    volumes:
    - name: products
      hostPath:
        path: "{{workflow.parameters.product_host_path}}"