{{/*
MIT License

(C) Copyright 2023-2024 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-product-catalog-template
  namespace: argo
  labels:
    version: "4.0.1"
spec:
  entrypoint: catalog-update
  templates:
  - name: catalog-update
    inputs:
      parameters:
        - name: cray-product-catalog-update-image
          value: "artifactory.algol60.net/csm-docker/stable/cray-product-catalog-update:2.0.1"
        - name: product-catalog-configmap-name
          value: "cray-product-catalog"
        - name: product-catalog-configmap-namespace
          value: "services"
        - name: product-name
        - name: product-version
        - name: yaml-content
    container:
      image: "{{inputs.parameters.cray-product-catalog-update-image}}"
      command: [catalog_update]
      env:
        - name: PRODUCT
          value: "{{inputs.parameters.product-name}}"
        - name: PRODUCT_VERSION
          value: "{{inputs.parameters.product-version}}"
        - name: CONFIG_MAP
          value: "{{inputs.parameters.product-catalog-configmap-name}}"
        - name: CONFIG_MAP_NAMESPACE
          value: "{{inputs.parameters.product-catalog-configmap-namespace}}"
        - name: YAML_CONTENT_STRING
          value: "{{inputs.parameters.yaml-content}}"
        - name: VALIDATE_SCHEMA
          value: "true"
        - name: REMOVE_ACTIVE_FIELD
          value: "true"
