#
# MIT License
#
# (C) Copyright 2022-2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: cray-nls.hpe.com/v1
kind: Hook
metadata:
  name: ensure-etcd-pods-are-healthy
  labels:
    before-each: "true"
spec:
  # sort out kube-etcd-defrag-cray-hbtd-bitnami-etcd-*
  scriptContent: |
    #!/bin/sh
    while true; do
        pods=$(kubectl get po -A  -o json | jq -r '.items[] | select(.metadata.annotations."kubectl.kubernetes.io/default-container"=="etcd") | (.metadata.name + " " + .status.phase)')
        if [ "$(echo "${pods}" | awk '{ print $2 }' | sort -u)" == Running ]; then
            break
        fi
        echo "Some etcd pods are not in running state, wait for 5s ..."
        echo "${pods}" | grep -v Running
        sleep 5
    done
  templateRefName: ssh-template
