#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: echo-template
  labels:
    version: "4.0.1"
spec:
  entrypoint: echo-message
  templates:
    - name: echo-message
      inputs:
       parameters:
         - name: message
           description: >
             The message you want to echo
         - name: isError
           description: >
             A flag indicating whether to exit 1 or exit 0.
             True means exit 1.
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      script:
        image: artifactory.algol60.net/csm-docker/stable/iuf:csm-latest
        command: [sh]
        source: |
          #!/host_usr_bin/bash
          IS_ERROR={{inputs.parameters.isError}}
          if [[ "${IS_ERROR}" == "true" ]];then
            echo "ERROR {{inputs.parameters.message}}"
            exit 1
          else
            echo "INFO {{inputs.parameters.message}}"
            exit 0
          fi
        volumeMounts:
          # mount csi from host to docker
          # csi is go compiled so it can be used from host to container
          - name: host-usr-bin
            mountPath: /host_usr_bin
          - name: ca-bundle
            mountPath: /var/lib/ca-certificates
          - name: iuf
            mountPath: /etc/cray/upgrade/csm
