apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-pod
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-pod
subjects:
- kind: ServiceAccount
  name: postgres-pod
  namespace: services
- kind: ServiceAccount
  name: postgres-pod
  namespace: spire
- kind: ServiceAccount
  name: postgres-pod
  namespace: argo
- kind: ServiceAccount
  name: postgres-pod
  namespace: sma
