#!/usr/bin/env bash
#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

set -o errexit
set -o pipefail

usage() {
    echo >&2 "usage: ${0##*/} [-i] [CUSTOMIZATIONS-YAML]"
    exit 1
}

args=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h)
            usage
            ;;
        -i)
            inplace="yes"
            ;;
        *)
            args+=("$1")
            ;;
    esac
    shift
done

set -- "${args[@]}"

[[ $# -eq 1 ]] || usage

set -o xtrace

customizations="$1"

if [[ ! -f "$customizations" ]]; then
    echo >&2 "error: no such file: $customizations"
    usage
fi

c="$(mktemp)"
trap "rm -f '$c'" EXIT

cp "$customizations" "$c"

# Add new PowerDNS values that would be generated by CSI on a fresh install

yq write -i "$c" 'spec.network.dns.primary_server_name' primary
yq write -i --style=double "$c" 'spec.network.dns.secondary_servers' ""
yq write -i --style=double "$c" 'spec.network.dns.notify_zones' ""

# Add new generator for the PowerDNS API key Sealed Secret
yq write -i "$c" 'spec.kubernetes.sealed_secrets.powerdns.generate.name' cray-powerdns-credentials
yq write -i "$c" 'spec.kubernetes.sealed_secrets.powerdns.generate.data[0].type' randstr
yq write -i "$c" 'spec.kubernetes.sealed_secrets.powerdns.generate.data[0].args.name' pdns_api_key
yq write -i "$c" 'spec.kubernetes.sealed_secrets.powerdns.generate.data[0].args.length' 32

# Add new generator for the dnssec key
yq write -i "$c" 'spec.kubernetes.sealed_secrets.dnssec.generate.name' dnssec-keys
yq write -i "$c" 'spec.kubernetes.sealed_secrets.dnssec.generate.data[0].type' static_b64
yq write -i "$c" 'spec.kubernetes.sealed_secrets.dnssec.generate.data[0].args.name' dummy
yq write -i "$c" 'spec.kubernetes.sealed_secrets.dnssec.generate.data[0].args.value' ZHVtbXkK

# Delete unused externaldns configuraation
yq delete -i "$c" 'spec.kubernetes.services.cray-externaldns'

yq write -i "$c" 'spec.kubernetes.services.cray-dns-unbound.domain_name' '{{ network.dns.external }}'
yq write -i --style=double "$c" 'spec.kubernetes.services.cray-powerdns-manager.manager.primary_server' '{{ network.dns.primary_server_name }}/{{ network.netstaticips.site_to_system_lookups }}'
yq write -i --style=double "$c" 'spec.kubernetes.services.cray-powerdns-manager.manager.secondary_servers' "{{ network.dns.secondary_servers }}"
yq write -i --style=double "$c" 'spec.kubernetes.services.cray-powerdns-manager.manager.base_domain' "{{ network.dns.external }}"
yq write -i --style=double "$c" 'spec.kubernetes.services.cray-powerdns-manager.manager.notify_zones' "{{ network.dns.notify_zones }}"
yq write -i "$c" 'spec.kubernetes.services.cray-powerdns-manager.cray-service.sealedSecrets[0]' '{{ kubernetes.sealed_secrets.dnssec | toYaml }}'
yq write -i "$c" 'spec.kubernetes.services.cray-dns-powerdns.service.can.loadBalancerIP' '{{ network.netstaticips.site_to_system_lookups }}'
yq write -i "$c" 'spec.kubernetes.services.cray-dns-powerdns.cray-service.sealedSecrets[0]' '{{ kubernetes.sealed_secrets.powerdns | toYaml }}'

if [[ "$inplace" == "yes" ]]; then
    cp "$c" "$customizations"
else
    cat "$c"
fi
