#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: add-storage-node-to-ceph
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: targetNcn
          - name: dryRun
          - name: workflowType
      dag:
        tasks:
          - name: copy-ceph-pub
            templateRef:
              name: ssh-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{inputs.parameters.dryRun}}"
                - name: scriptContent
                  value: |
                    TARGET_NCN="{{inputs.parameters.targetNcn}}"
                    ceph cephadm get-pub-key > ~/ceph.pub
                    ssh-copy-id -f -i ~/ceph.pub root@${TARGET_NCN}
          - name: update-ssh-keys
            templateRef:
              name: ssh-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{inputs.parameters.dryRun}}"
                - name: scriptContent
                  value: |
                    TARGET_NCN="{{inputs.parameters.targetNcn}}"
                    TARGET_NCN_ip=$(host ${TARGET_NCN} | awk '{ print $NF }')
                    echo "Updating ssh keys to rebuilt/upgraded node"
                    . ${basedir}/../common/ncn-common.sh ${TARGET_NCN}
                    ssh_keygen_keyscan "${TARGET_NCN}"
                    # Add ssh keys to ncn-s00[1/2/3]
                    for node in "ncn-s001" "ncn-s002" "ncn-s003"; do
                      ssh $node "ssh-keyscan -H ${TARGET_NCN},${TARGET_NCN_ip} >> ~/.ssh/known_hosts"
                    done
          - name: pull-images-from-nexus
            templateRef:
              name: ssh-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{inputs.parameters.dryRun}}"
                - name: scriptContent
                  value: |
                    TARGET_NCN="{{inputs.parameters.targetNcn}}"
                    for container in "container_image_prometheus" "container_image_node_exporter" "container_image_alertmanager" "container_image_grafana"; do
                        image=$(ceph config get mgr mgr/cephadm/${container})
                        ssh ${target_ncn} podman pull $image
                    done
                    ssh ${target_ncn} podman pull "$(cat /tmp/ceph_global_container_image.txt)"
          - name: restore-ceph-files
            dependencies:
              - update-ssh-keys
            template: restore-ceph-files-from-tar
            when: "{{inputs.parameters.workflowType}} == rebuild"
            arguments:
              parameters:
                - name: dryRun
                  value: "{{inputs.parameters.dryRun}}"
                - name: targetNcn
                  value: "{{inputs.parameters.targetNcn}}"
          - name: restore-ceph-files
            dependencies:
              - update-ssh-keys
            template: copy-ceph-files-from-storage-node
            when: "{{inputs.parameters.workflowType}} == upgrade"
            arguments:
              parameters:
                - name: dryRun
                  value: "{{inputs.parameters.dryRun}}"
                - name: targetNcn
                  value: "{{inputs.parameters.targetNcn}}"
          - name: add-host
            dependencies:
              - copy-ceph-pub
              - restore-ceph-files
              - pull-images-from-nexus
            templateRef:
              name: ssh-template
              template: shell-script
            arguments:
              parameters:
                - name: dryRun
                  value: "{{inputs.parameters.dryRun}}"
                - name: scriptContent
                  value: |
                    TARGET_NCN="{{inputs.parameters.targetNcn}}"
                    ceph orch host add $TARGET_NCN
                    sleep 5
                    ceph orch host label rm $TARGET_NCN _no_schedule
          
    ### Templates referenced by main DAG
    # this is used when a storage node is being rebuilt
    - name: copy-ceph-files-from-storage-node
      inputs:
        parameters:
          - name: dryRun
          - name: targetNcn
      dag:
        tasks:
          - name: copy-ceph-files
            templateRef:
              name: ssh-template
              template: shell-script
            arguments:
              parameters:
              - name: dryRun
                value: "{{inputs.parameters.dryRun}}"
              - name: scriptContent
                value: |
                  TARGET_NCN="{{inputs.parameters.targetNcn}}"
                  for node in ncn-s001 ncn-s002 ncn-s003; do
                    if [[ "$TARGET_NCN" == "$node" ]]; then
                      continue
                    else
                      if [[ "$TARGET_NCN" =~ ^("ncn-s001"|"ncn-s002"|"ncn-s003")$ ]]
                      then
                        scp $node:/etc/ceph/\{rgw.pem,ceph.conf,ceph_conf_min,ceph.client.ro.keyring,ceph.client.admin.keyring\} ${TARGET_NCN}:/etc/ceph
                      else
                        scp $node:/etc/ceph/\{rgw.pem,ceph.conf,ceph_conf_min,ceph.client.ro.keyring\}  ${TARGET_NCN}:/etc/ceph/
                      fi
                      break
                    fi
                  done
                  # copy ceph.client.ro.keyring
                  if ! $(ceph auth get client.ro >/dev/null 2>/dev/null); then
                    ceph-authtool -C /etc/ceph/ceph.client.ro.keyring -n client.ro --cap mon 'allow r' --cap mds 'allow r' --cap osd 'allow r' --cap mgr 'allow r' --gen-key
                  fi
                  if [ -f "/etc/ceph/ceph.client.ro.keyring" ]; then
                    ceph auth import -i /etc/ceph/ceph.client.ro.keyring
                  else
                    ceph auth get client.ro -o /etc/ceph/ceph.client.ro.keyring
                    ceph auth import -i /etc/ceph/ceph.client.ro.keyring
                  fi
                  for node in $(ceph orch host ls --format=json|jq -r '.[].hostname'); do scp /etc/ceph/ceph.client.ro.keyring $node:/etc/ceph/ceph.client.ro.keyring; done
                  scp /etc/ceph/ceph.client.ro.keyring ${TARGET_NCN}:/etc/ceph/ceph.client.ro.keyring
    # this is used when a storage node is being upgraded
    - name: restore-ceph-files-from-tar
      inputs:
        parameters:
          - name: dryRun
          - name: targetNcn
      dag:
        tasks:
          - name: restore-ceph-files
            templateRef:
              name: ssh-template
              template: shell-script
            arguments:
              parameters:
              - name: dryRun
                value: "{{inputs.parameters.dryRun}}"
              - name: scriptContent
                value: |
                  TARGET_NCN="{{inputs.parameters.targetNcn}}"
                  scp ./${TARGET_NCN}-ceph.tgz $TARGET_NCN:/
                  ssh ${TARGET_NCN} 'cd /; tar -xvf ./$(hostname)-ceph.tgz; rm /$(hostname)-ceph.tgz'
