#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

apiVersion: batch/v1
kind: Job
metadata:
  generateName: upgrade-k8s-job-
  namespace: argo
spec:
  completions: 1
  backoffLimit: 25
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"  # Disable sidecar injection for this Job's pod
    spec:
      containers:
      - name: upgrade-k8s-job
        image: artifactory.algol60.net/csm-docker/stable/docker.io/alpine/git:2.32.0
        command: ["sh", "-c"]
        args:
        - |
          ssh -i /myssh/id_rsa -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null root@ncn-m001 \
              "set -o pipefail; \
               ts=\$(date +'%Y-%m-%d_%H-%M-%S'); \
               /usr/share/doc/csm/upgrade/scripts/k8s/upgrade_k8s_steps.sh 2>&1 | tee /root/upgrade_k8s_output_\$ts.log"
        volumeMounts:
        - mountPath: /myssh
          name: ssh
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/hostname: ncn-m001
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
      - name: ssh
        hostPath:
          path: /root/.ssh

