apiVersion: cray-nls.hpe.com/v1
kind: Hook
metadata:
  name: ensure-etcd-pods-are-healthy
  labels:
    before-each: "true"
spec:
  scriptContent: |
    while [[ "$(kubectl get po -A -l 'app=cray-etcd-operator-etcd-operator-etcd-operator' | grep -v "Running"| wc -l)" != "1" ]]; do
        echo "Etcd operator is not in running state, wait for 5s ..."
        kubectl get po -A -l 'app=cray-etcd-operator-etcd-operator-etcd-operator' | grep -v "Running"
        sleep 5
    done

    export GOSS_BASE=/opt/cray/tests/install/ncn
    GOSS_ARG="--vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate \
      --retry-timeout 1h \
      --sleep 1m"

    goss -g /opt/cray/tests/install/ncn/tests/goss-cray-service-etcd-health-check.yaml  ${GOSS_ARG}

    while [[ "$(kubectl get po -A -l 'app=etcd' | grep -v "Running"| wc -l)" != "1" ]]; do
        echo "Some etcd pods are not in running state, wait for 5s ..."
        kubectl get po -A -l 'app=etcd' | grep -v "Running"
        sleep 5
    done

    etcdClusters=$(kubectl get Etcdclusters -n services | grep "cray-"|awk '{print $1}')
    for cluster in $etcdClusters
    do
        while true; do
          numOfPods=$(kubectl get pods -A -l 'app=etcd'| grep $cluster | grep "Running" | wc -l)
          if [[ $numOfPods -ne 3 ]];then
            echo "ERROR - Etcd cluster: $cluster should have 3 pods running but only $numOfPods are running"
            continue
          else
            echo "Etcd cluster: $cluster have 3 pods running"
            break
          fi
        done
    done
  templateRefName: ssh-template
