#!/bin/bash
#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

# Usage: generate_customization-secrets.sh <path-to-customizations.yaml>
#
# This assumes it is being run in the context of the install/prepare_site_init.md procedure

set -eou pipefail

SSC_BASENAME=secrets-seed-customizations.sh
DECRYPT_BASENAME=secrets-decrypt.sh
SSCRT_BASENAME=sealed_secrets.crt
SSKEY_BASENAME=sealed_secrets.key

function err_exit {
  echo "ERROR: $*" >&2
  exit 1
}

function dir_exists {
  while [[ $# -gt 0 ]]; do
    [[ -e $1 ]] || err_exit "Directory does not exist: '$1'"
    [[ -d $1 ]] || err_exit "Exists but is not a directory: '$1'"
    shift
  done
}

function file_exists {
  while [[ $# -gt 0 ]]; do
    [[ -e $1 ]] || err_exit "File does not exist: '$1'"
    [[ -f $1 ]] || err_exit "Exists but is not a regular file: '$1'"
    [[ -s $1 ]] || err_exit "File exists but is 0 size: '$1'"
    shift
  done
}

[[ $# -eq 1 ]] || err_exit "Script takes exactly 1 argument but received $#. Invalid argument(s): $*"

if [[ $1 == -h || $1 == --help ]]; then
  echo "usage: $0 <full path to site-init customizations.yaml>" >&2
  exit 2
fi

[[ -n $1 ]] || err_exit "Argument may not be blank"
[[ -e $1 ]] || err_exit "Specified file does not exist: '$1'"
[[ -f $1 ]] || err_exit "Exists but is not a regular file: '$1'"
CUSTOMIZATIONS="$1"

SITE_INIT=$(dirname "${CUSTOMIZATIONS}")
UTILS="${SITE_INIT}/utils"
CERTS="${SITE_INIT}/certs"
dir_exists "${UTILS}" "${CERTS}"

# Make sure the necessary scripts and certs exist

SSC="${UTILS}/${SSC_BASENAME}"
DECRYPT="${UTILS}/${DECRYPT_BASENAME}"
SEALED_SECRETS_KEY="${CERTS}/${SSKEY_BASENAME}"
SEALED_SECRETS_CERT="${CERTS}/${SSCRT_BASENAME}"

file_exists "${SSC}" "${DECRYPT}" "${SEALED_SECRETS_KEY}" "${SEALED_SECRETS_CERT}"
[[ -x ${SSC} ]] || err_exit "Exists but is not executable: '${SSC}'"
[[ -x ${DECRYPT} ]] || err_exit "Exists but is not executable: '${DECRYPT}'"

echo "Making backup copy of '${CUSTOMIZATIONS}'"
cp -v "${CUSTOMIZATIONS}" "${CUSTOMIZATIONS}.$(date '+%y%m%d_%H%M%S_%N').before_url_safe_fix"

# CASMINST-7236: This is to work around CASMTRIAGE-7072 on CSM versions without the fix for CASMINST-6897
echo "Correcting value of url_safe fields, if needed"
sed -i 's/^\([[:space:]]*url_safe:[[:space:]]\+\)true[[:space:]]*$/\1yes/' "${CUSTOMIZATIONS}"

echo "Making backup copy of '${CUSTOMIZATIONS}' before generating secrets"
POST_SED_BACKUP="${CUSTOMIZATIONS}.$(date '+%y%m%d_%H%M%S_%N').after_url_safe_fix"
cp -v "${CUSTOMIZATIONS}" "${POST_SED_BACKUP}"

echo "Generating secrets"
"${SSC}" "${CUSTOMIZATIONS}"

# CASMINST-7236: Double check that all URL safe credentials are actually URL safe, since fixing this post-install
# is significantly more painful
echo "Validating that secrets were generated correctly"

# Make a list of all credentials generated by randstr as url_safe base64
URL_SAFE_LIST=$(yq r -j "${POST_SED_BACKUP}" spec.kubernetes.sealed_secrets | python3 -c '
import sys, json
secrets = json.load(sys.stdin)
for secret_name, secret_info in secrets.items():
    if "generate" not in secret_info:
        continue
    gen_info = secret_info["generate"]
    data_name_list = []
    for data in gen_info.get("data",[]):
        if data.get("type") != "randstr":
            continue
        if data.get("args",{}).get("url_safe") not in { "true", "yes" }:
            continue
        if data.get("args",{}).get("encoding") == "hex":
            continue
        data_name = data.get("args",{}).get("name")
        if data_name:
            data_name_list.append(data_name)
    if not data_name_list:
        continue
    data_names = "|".join(data_name_list)
    print(f"{secret_name},{data_names}")
')

# Return 0 if all data names have URL safe decoded values
# Return 1 otherwise
function check_data {
  for DATA_NAME in "${DATA_NAMES[@]}"; do
    DATA_PATH=.data."\"${DATA_NAME}\""
    "${DECRYPT}" "${SECRET_NAME}" "${SEALED_SECRETS_KEY}" "${CUSTOMIZATIONS}" | jq -r "${DATA_PATH}" | base64 --decode | grep -Eq '[+/]' || continue
    return 1
  done
  return 0
}

for U in ${URL_SAFE_LIST}; do
  SECRET_NAME=${U%%,*}
  IFS='|' read -ra DATA_NAMES <<< "${U##*,}"
  echo "Checking ${SECRET_NAME}"
  while ! check_data; do
    echo "Regenerating"
    SECRET_PATH=spec.kubernetes.sealed_secrets."\"${SECRET_NAME}\""
    yq delete -i "${CUSTOMIZATIONS}" "${SECRET_PATH}"
    yq r "${POST_SED_BACKUP}" "${SECRET_PATH}" | yq w -i "${CUSTOMIZATIONS}" -f - "${SECRET_PATH}"
    "${SSC}" "${CUSTOMIZATIONS}"
  done
  echo "Done checking ${SECRET_NAME}"
done

echo "Done!"
