apiVersion: cray-nls.hpe.com/v1
kind: Hook
metadata:
  name: update-bss-no-wipe
  labels:
    after-each: "true"
spec:
  scriptContent: |
    TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
    TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
        jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
    /host_usr_bin/csi handoff bss-update-param --set metal.no-wipe=1 --limit $TARGET_XNAME
  templateRefName: kubectl-and-curl-template
