name: backport
 
on:
  pull_request:
    types:
      - closed
      - labeled
      - unlabeled

jobs:
  backport:
    name: "${{ github.event.action == 'closed' && 'backport' || 'dry run' }}"
    runs-on: self-hosted
    steps:
      - uses: Cray-HPE/backport-action@v3