name: shfmt
on:
  pull_request:

jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v46
      with:
        files: "**/*.sh"
        files_ignore: |
          .github/**/*
          api/*

    - uses: docker://mvdan/shfmt:v3
      if: ${{ steps.changed-files.outputs.all_changed_files }}
      with:
        args: -ci -s -i 2 -bn -sr -d ${{ steps.changed-files.outputs.all_changed_files }}
