name: Tag Head of Release Branches and Publish docs-csm RPM 

on:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * *'

concurrency:
  group: tag-and-publish 

jobs:
  tag-and-publish:
    runs-on: [self-hosted, self-hosted-small]
    name: Tag and Publish 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: release/1.3 Increment and Tag Head 
        run: |
          .github/scripts/increment-tag-head.sh release/1.3 
      
      - name: release/1.4 Increment and Tag Head 
        run: |
          .github/scripts/increment-tag-head.sh release/1.4 
